# Generated by Django 3.2 on 2025-03-12 17:57

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя инструктора')),
                ('bio', models.TextField(verbose_name='Биография инструктора')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар инструктора')),
                ('room_photo', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Инструктор',
                'verbose_name_plural': 'Инструкторы',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[main.models.validate_video_file_size, main.models.validate_file_extension], verbose_name='Видео приветствия')),
                ('background_photo', models.ImageField(blank=True, null=True, upload_to='images/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Фоновое изображение')),
                ('big_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Большой текст (на первой фотографии)')),
                ('small_text', models.TextField(blank=True, max_length=255, null=True, verbose_name='Малый текст')),
                ('overlay_video_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст на видео')),
                ('discount_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название скидки')),
                ('discount_description', models.TextField(blank=True, null=True, verbose_name='Описание скидки')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент скидки')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена без скидки')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Изображение сертификата')),
                ('tg_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram ID')),
                ('event_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание мероприятий')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.instructor', verbose_name='Инструктор')),
            ],
            options={
                'verbose_name': 'Контент главной страницы',
                'verbose_name_plural': 'Контент главной страницы',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='homepage_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.homepagecontent', verbose_name='Контент главной страницы'),
        ),
    ]
