# Generated by Django 3.2 on 2025-03-12 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя инструктора')),
                ('bio', models.TextField(verbose_name='Биография инструктора')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар инструктора')),
            ],
            options={
                'verbose_name': 'Инструктор',
                'verbose_name_plural': 'Инструкторы',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео приветствия')),
                ('background_photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фоновое изображение')),
                ('big_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Большой текст (на первой фотографии)')),
                ('small_text', models.TextField(blank=True, null=True, verbose_name='Малый текст')),
                ('diver_model_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на 3D модель')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.instructor', verbose_name='Инструктор')),
            ],
            options={
                'verbose_name': 'Контент главной страницы',
                'verbose_name_plural': 'Контент главной страницы',
            },
        ),
    ]
