# Generated by Django 3.2 on 2025-03-12 10:11

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='overlay_video_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст на видео'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='welcome_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[main.models.validate_video_file_size, main.models.validate_file_extension], verbose_name='Видео приветствия'),
        ),
    ]
