# Generated by Django 3.2 on 2025-03-13 15:19

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpage',
            name='training_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[main.models.validate_video_file_size, main.models.validate_file_extension], verbose_name='Видео обучения'),
        ),
    ]
