# Generated by Django 3.2 on 2025-03-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingimage',
            options={'verbose_name': 'Изображение курса', 'verbose_name_plural': 'Изображения курсов'},
        ),
        migrations.AlterModelOptions(
            name='trainingpage',
            options={'verbose_name': 'Страница обучения', 'verbose_name_plural': 'Страницы обучения'},
        ),
        migrations.AlterModelOptions(
            name='trainingvideo',
            options={'verbose_name': 'Видео курса', 'verbose_name_plural': 'Видео курсов'},
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='level',
        ),
        migrations.RemoveField(
            model_name='trainingimage',
            name='training_page',
        ),
        migrations.RemoveField(
            model_name='trainingvideo',
            name='training_page',
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='certificate',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сертификат'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='course_category',
            field=models.CharField(choices=[('regular', 'Обычный курс'), ('specialization', 'Специализация'), ('first_aid', 'Первая помощь')], default='regular', max_length=20, verbose_name='Тип курса'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='duration',
            field=models.CharField(default='0 часов', max_length=100, verbose_name='Длительность курса'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='included',
            field=models.TextField(default='Описание по умолчанию', verbose_name='Что входит в курс'),
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='international_certificate',
            field=models.BooleanField(default=False, verbose_name='Международный сертификат'),
        ),
        migrations.AddField(
            model_name='trainingimage',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.trainingcourse', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='course',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.trainingcourse', verbose_name='Курс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='training_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.trainingpage', verbose_name='Страница обучения'),
        ),
        migrations.AlterField(
            model_name='trainingimage',
            name='image',
            field=models.ImageField(upload_to='training_images/', verbose_name='Изображение курса'),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='video',
            field=models.FileField(upload_to='training_videos/', verbose_name='Видео курса'),
        ),
    ]
