# Generated by Django 3.2 on 2025-03-13 08:04

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название оборудования')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='equipment/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='EquipmentPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Снаряжение для дайвинга', max_length=255, verbose_name='Заголовок страницы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание страницы')),
                ('background_photo', models.ImageField(blank=True, null=True, upload_to='equipment_page/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Фоновое изображение')),
                ('equipment', models.ManyToManyField(blank=True, related_name='equipment_page', to='main.Equipment', verbose_name='Список оборудования')),
            ],
            options={
                'verbose_name': 'Контент страницы оборудования',
                'verbose_name_plural': 'Контент страницы оборудования',
            },
        ),
    ]
