# Generated by Django 3.2 on 2025-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250328_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingcourse',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='international_certificate',
        ),
        migrations.RemoveField(
            model_name='trainingcourse',
            name='price',
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='course_category',
            field=models.CharField(choices=[('regular', 'Обычные курсы'), ('sdi_specialization', 'Специализации SDI'), ('first_response', 'Курсы первой медицинской помощи')], default='regular', max_length=20, verbose_name='Тип курса'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='included',
            field=models.TextField(verbose_name='Что входит в курс'),
        ),
    ]
