# Generated by Django 3.2 on 2025-03-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250312_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='small_text',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Малый текст'),
        ),
    ]
