# Generated by Django 3.2 on 2025-03-13 17:35

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_trainingpage_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trainingpage',
            name='training_video',
        ),
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='training_videos/', validators=[main.models.validate_video_file_size, main.models.validate_file_extension], verbose_name='Видео')),
                ('training_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.trainingpage', verbose_name='Страница обучения')),
            ],
            options={
                'verbose_name': 'Видео обучения',
                'verbose_name_plural': 'Видео обучения',
            },
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training_images/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Изображение')),
                ('training_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.trainingpage', verbose_name='Страница обучения')),
            ],
            options={
                'verbose_name': 'Изображение обучения',
                'verbose_name_plural': 'Изображения обучения',
            },
        ),
    ]
