# Generated by Django 3.2 on 2025-03-12 10:46

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_homepagecontent_small_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='discount_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание скидки'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='discount_image',
            field=models.ImageField(blank=True, null=True, upload_to='discounts/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Изображение скидки'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='discount_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название скидки'),
        ),
    ]
