# Generated by Django 3.2 on 2025-03-29 06:47

from django.db import migrations, models
import django.utils.timezone
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250328_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='certificates/', validators=[main.validators.validate_image_file_size, main.validators.validate_file_extension], verbose_name='Изображение сертификата')),
                ('title', models.CharField(max_length=100, verbose_name='Название сертификата')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сертификата')),
                ('validity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок действия сертификата')),
                ('terms', models.TextField(blank=True, null=True, verbose_name='Условия использования сертификата')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='certificate_description',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='certificate_price',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='certificate_terms',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='certificate_title',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='certificate_validity',
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='certificates',
            field=models.ManyToManyField(blank=True, to='main.Certificate', verbose_name='Сертификаты'),
        ),
    ]
