# Generated by Django 3.2 on 2025-03-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20250329_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Ремонт оборудования', 'verbose_name_plural': 'Ремонт оборудования'},
        ),
        migrations.AlterModelOptions(
            name='equipmentpagecontent',
            options={'verbose_name': 'Контент страницы ремонта оборудования', 'verbose_name_plural': 'Контент страницы ремонта оборудования'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Подробная информация о ремонтных работах и услугах', null=True, verbose_name='Подробное описание ремонта'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='equipmentpagecontent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Вступительный текст страницы'),
        ),
        migrations.AlterField(
            model_name='equipmentpagecontent',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='equipment_page', to='main.Equipment', verbose_name='Список ремонтируемого оборудования'),
        ),
        migrations.AlterField(
            model_name='equipmentpagecontent',
            name='title',
            field=models.CharField(default='Ремонт оборудования', max_length=255, verbose_name='Заголовок страницы'),
        ),
    ]
