# Generated by Django 3.2 on 2025-03-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20250313_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('introduction', models.TextField(verbose_name='Введение')),
                ('team_description', models.TextField(verbose_name='Наша команда')),
                ('mission', models.TextField(verbose_name='Наша миссия')),
                ('services', models.TextField(verbose_name='Наши услуги')),
                ('contact_info', models.TextField(verbose_name='Связь с нами')),
            ],
            options={
                'verbose_name': 'Страница о нас',
                'verbose_name_plural': 'Страница о нас',
            },
        ),
    ]
