# Generated by Django 3.2 on 2025-03-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20250312_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='discount_image',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена без скидки'),
        ),
    ]
