# Generated by Django 3.2 on 2025-03-12 11:03

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20250312_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Изображение сертификата'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='tg_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram ID'),
        ),
    ]
