# Generated by Django 3.2 on 2025-03-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='contact_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='introduction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='services',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
