# Generated by Django 3.2 on 2025-03-13 19:26

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20250313_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='team_description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/mission_image/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Изображение миссии'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_photo',
            field=models.ImageField(blank=True, null=True, upload_to='about/mission/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Фото миссии'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_statement',
            field=models.TextField(default='', verbose_name='Наша миссия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='services_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/services_image/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Изображение услуг'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='social_links',
            field=models.JSONField(blank=True, null=True, verbose_name='Ссылки на соцсети'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='contact_info',
            field=models.TextField(verbose_name='Связь с нами'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='introduction',
            field=models.TextField(verbose_name='Введение'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='services',
            field=models.TextField(verbose_name='Наши услуги'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_photo',
            field=models.ImageField(blank=True, null=True, upload_to='about/team/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Фото команды'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
