# Generated by Django 3.2 on 2025-03-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20250313_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission',
            field=models.TextField(blank=True, null=True, verbose_name='Наша миссия'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание команды'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
