# Generated by Django 3.2 on 2025-03-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20250313_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mission',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/team/', verbose_name='Изображение команды'),
        ),
    ]
