# Generated by Django 3.2 on 2025-03-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20250313_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='instructors',
            field=models.ManyToManyField(blank=True, to='main.Instructor', verbose_name='Инструкторы'),
        ),
    ]
