# Generated by Django 3.2 on 2025-03-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aboutpage_instructors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone_numbers', models.JSONField(default=list)),
                ('email', models.EmailField(max_length=254)),
                ('map_link', models.URLField()),
                ('social_links', models.JSONField(default=dict)),
            ],
        ),
    ]
