# Generated by Django 3.2 on 2025-03-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contactpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Контактная страница', 'verbose_name_plural': 'Контактные страницы'},
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='map_link',
            field=models.URLField(verbose_name='Ссылка на карту'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone_numbers',
            field=models.JSONField(default=list, verbose_name='Телефонные номера'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='social_links',
            field=models.JSONField(default=dict, verbose_name='Социальные сети'),
        ),
    ]
