# Generated by Django 3.2 on 2025-03-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Политика конфиденциальности', 'verbose_name_plural': 'Политика конфиденциальности'},
        ),
        migrations.AlterModelOptions(
            name='termsofservice',
            options={'verbose_name': 'Правила пользования', 'verbose_name_plural': 'Правила пользования'},
        ),
    ]
