# Generated by Django 3.2 on 2025-03-21 10:37

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20250317_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='discount_description',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='discount_title',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='trainingpage',
            name='advanced_courses',
        ),
        migrations.RemoveField(
            model_name='trainingpage',
            name='beginner_courses',
        ),
        migrations.RemoveField(
            model_name='trainingpage',
            name='professional_courses',
        ),
        migrations.RemoveField(
            model_name='trainingpage',
            name='tech_courses',
        ),
        migrations.RemoveField(
            model_name='event',
            name='homepage_content',
        ),
        migrations.AddField(
            model_name='event',
            name='homepage_content',
            field=models.ManyToManyField(blank=True, related_name='events', to='main.HomePageContent', verbose_name='Контент главной страницы'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Курсы для новичков'), ('advanced', 'Продвинутые курсы'), ('professional', 'Профессиональные курсы'), ('tech', 'Технический дайвинг')], max_length=20, verbose_name='Уровень курса')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('training_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.trainingpage')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название скидки')),
                ('discount_description', models.TextField(blank=True, null=True, verbose_name='Описание скидки')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент скидки')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена без скидки')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='main.homepagecontent', verbose_name='Контент главной страницы')),
            ],
        ),
    ]
