# Generated by Django 3.2 on 2025-03-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20250321_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='big_text',
            field=models.TextField(blank=True, null=True, verbose_name='Большой текст (на первой фотографии)'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='small_text',
            field=models.TextField(blank=True, null=True, verbose_name='Малый текст'),
        ),
    ]
