# Generated by Django 3.2 on 2025-03-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20250321_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='discount_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание скидки'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='discount_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название скидки'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена без скидки'),
        ),
    ]
