# Generated by Django 3.2 on 2025-03-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20250321_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент скидки'),
        ),
    ]
