# Generated by Django 3.2 on 2025-03-21 16:04

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_homepagecontent_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='small_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Малое изображение'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[main.models.validate_image_file_size, main.models.validate_file_extension], verbose_name='Большое изображение'),
        ),
    ]
