# Generated by Django 3.2 on 2025-03-23 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20250321_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='tg_id',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='certificate_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание сертификата'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='certificate_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена сертификата'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='certificate_terms',
            field=models.TextField(blank=True, null=True, verbose_name='Условия использования сертификата'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='certificate_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название сертификата'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='certificate_validity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Срок действия сертификата'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='discount_validity',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия скидки'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки'),
        ),
    ]
