# Generated by Django 3.2 on 2025-03-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20250323_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Скидоооон'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Скидоооон'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скидоооон'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Скидоооон'),
        ),
    ]
