# Generated by Django 3.2 on 2025-03-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20250323_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
